name: "🏃‍♂️Sprint review"
description: Sprint 회고를 해봅시다!
title: "[Sprint-#] Liked Learned Lacked"
labels: [
  "sprint-review"
]
body:
  - type: textarea
    id: raccoon
    attributes:
      label: "raccoon"
      description: raccoon의 소감은 어땠나요?
      value: "- "
    validations:
      required: true
  - type: textarea
    id: otter
    attributes:
      label: "otter"
      description: otter의 소감은 어땠나요?
      value: "- "
    validations:
      required: true